### ISSUE TITLE
Trying to import the kids450_cf_likelihood_public likelihood failed

### ISSUE THREAD

**Issue by JaimeRZP** [fkoehlin/kids450_cf_likelihood_public#1]
Dear Mr/Ms,

My name is Jaime and I am an UCL undergrad currently undertaking a summer project.  I am having some issues trying to run the code. 
I have carefully followed all the steps of the installation and I am currently trying to run the code within Montepython using:
'python montepython/MontePython.py  run -o test -p input/kids450_cf.param'

However, I get the following error message:
'Trying to import the kids450_cf_likelihood_public likelihood as asked in
 the parameter file, and failed. Please make sure it is in the
Montepython/likelihoods` folder, and is a proper python module. Check
also that the name of the class defined in the __init__.py matches the
name of the folder. In case this is not enough, here is the original
message: cannot import name solve_triangular'

I have made sure that I have the compatible python (2.6.6) and class (2.7.2) versions  and he __init__.py file inside the likelihood and the .param file quote the right likelihood folder, the folder is in the correct directory, the content of the likelihood folder contains both a .py and a .data file and that the montepython and montepython likelihoods directories contain the necessary empty __init__.py to recognize likelihoods as python files. I have also tried running the code deleting the __init__.pyc files that are created during the runs in both directories.  

Moreover, I have tried repeating the installation and switching the likelihood called in the .param file and the program runs fine so it seems to be a simple problem with the folder allocation of the kids likelihood but I cannot figure it out. 

Do you know how could this issue be solved? 

Thank you so much in advance.
All the best,
Jaime.

**Comment by fkoehlin** [comment]
Hi Jaime,

The last sentence of the error message you quote, i.e. 

> In case this is not enough, here is the original
> message: cannot import name solve_triangular

suggests that the Python package `scipy.linalg` is not installed / correctly set up on the machine you're trying to use for this runs.
Please make sure that `SciPy` is installed correctly and that you can import the `solve_triangular` function from the `scipy.linalg` subpackage.

Cheers,

Fabian

**Comment by JaimeRZP** [comment]
Dear Fabian,

This was extremely helpful! I was using a different python set up from the
one I thought I was using.
Everything runs fine now.

Thank you once again.
All the best,
Jaime
